# Generated by Django 3.1.7 on 2021-03-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation_participants',
            old_name='conversation_id',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='conversation_participants',
            old_name='participant_id',
            new_name='participant',
        ),
    ]
