# Generated by Django 3.1.7 on 2021-03-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_auto_20210317_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='description',
            field=models.TextField(max_length=75),
        ),
    ]
