# Generated by Django 3.1.7 on 2021-03-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_auto_20210317_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_link',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_permission',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
