# Generated by Django 3.1.7 on 2021-03-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_auto_20210318_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_permission',
            field=models.BooleanField(default=False),
        ),
    ]
